import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeContextProvider } from "@/context/theme";
import { useUserStore } from '@/stores/user.store'

import Header from "./components/base/header/Header";
import Footer from "./components/base/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  try {
    await useUserStore.getState().getUser()
  } catch (e) {
    console.log(e)
  }
  return (
    <html lang="uk">
      <ThemeContextProvider>
        <body className={inter.className}>
          <div id="root">
            <Header />
            <main className="flex flex-col">
              {children}
            </main>
            <Footer/>
          </div>
        </body>
      </ThemeContextProvider>
    </html>
  );
}
